import SwiftUI

// Auto-generated by Last Mile - do not edit manually
enum AppConfig {
    static let primaryColor      = Color(hex: "#F97316")
    static let accentColor       = Color(hex: "#EF4444")
    static let backgroundColor   = Color(hex: "#FFFFFF")
    static let fontDesign: Font.Design = .rounded
    static let preferredColorScheme: ColorScheme? = nil
    static let restaurantName    = "مطعمنا"
    static let restaurantTagline = "ألذ الأطباق الشرقية"
    static let menuItems: [(name: String, emoji: String, price: String, category: String)] = [
        ("كبسة لحم",    "🍖", "45", "رئيسية"),
        ("مندي دجاج",   "🍗", "38", "رئيسية"),
        ("حريرة",       "🍲", "18", "شوربة"),
        ("سلطة خضراء",  "🥗", "22", "سلطة"),
        ("كنافة",       "🍮", "25", "حلويات"),
        ("عصير برتقال", "🥤", "15", "مشروبات"),
    ]
}
